/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "check.h"

bool_t
xdr_request_access_token_input (XDR *xdrs, request_access_token_input *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->client_id, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->auth_token, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->refresh_duration))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_request_access_token_output (XDR *xdrs, request_access_token_output *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->resource_access_token, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->refresh_token, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->duration))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->request_response, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_validate_delegated_action_input (XDR *xdrs, validate_delegated_action_input *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->client_id, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->operation, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->resource, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->resource_access_token, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_validate_delegated_action_output (XDR *xdrs, validate_delegated_action_output *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->request_response, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->regenerated_resource_access_token, ~0))
		 return FALSE;
	return TRUE;
}
