/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "check.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include "server_data.h"

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

#define LINE_MAX_SIZE 128
int USER_ID_SIZE = 15;
int RESOURCES_MAX_SIZE = 20;
FILE *file3;
int id_count;
char **user_ids_list;
int resources_count;
char **resources_list;
int token_valability;

static void
checkprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		char *request_authorization_1_arg;
		struct request_access_token_input request_access_token_1_arg;
		struct validate_delegated_action_input validate_delegated_action_1_arg;
		char *approve_request_token_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case request_authorization:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) request_authorization_1_svc;
		break;

	case request_access_token:
		_xdr_argument = (xdrproc_t) xdr_request_access_token_input;
		_xdr_result = (xdrproc_t) xdr_request_access_token_output;
		local = (char *(*)(char *, struct svc_req *)) request_access_token_1_svc;
		break;

	case validate_delegated_action:
		_xdr_argument = (xdrproc_t) xdr_validate_delegated_action_input;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) validate_delegated_action_1_svc;
		break;

	case approve_request_token:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) approve_request_token_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (CHECKPROG, CHECKVERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, CHECKPROG, CHECKVERS, checkprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CHECKPROG, CHECKVERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, CHECKPROG, CHECKVERS, checkprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CHECKPROG, CHECKVERS, tcp).");
		exit(1);
	}

	// Get server data from files
	if (argc < 5) {
		printf ("usage: %s userIDs.db resources.db approvals.db token_availability(ex.: 1,2...n)\n", argv[0]);
		exit (1);
	}
	char *userIDs = argv[1];
	char *resources = argv[2];
	char *approvals = argv[3];
	char *token_availability_string = argv[4];
	token_valability = atoi(token_availability_string);

	// USERIDS.DB
    FILE *file1 = fopen(userIDs, "r");
    if (file1 == NULL) {
        perror("Error opening userIDs.db");
        return 1;  // Return an error code
    }

    char line[LINE_MAX_SIZE];
	fgets(line, sizeof(line), file1);
	id_count = atoi(line);
	user_ids_list = calloc(id_count, sizeof(char*));

	// Read each line from the file
	for (int i = 0; i < id_count; i++) {
		user_ids_list[i] = calloc(USER_ID_SIZE + 1, sizeof(char));
		fgets(line, sizeof(line), file1);
		// Copy the line to user_ids_list[i]
    	strncpy(user_ids_list[i], line, USER_ID_SIZE);
    	// Ensure null-termination
    	user_ids_list[i][USER_ID_SIZE] = '\0';
	}
	fclose(file1);

	// RESOURCES.DB
	FILE *file2 = fopen(resources, "r");
	fgets(line, sizeof(line), file2);
	resources_count = atoi(line);
	resources_list = calloc(id_count, sizeof(char*));
    if (file2 == NULL) {
        perror("Error opening resources.db");
        return 1;  // Return an error code
    }
    // Read each line from the file
	for (int i = 0; i < resources_count; i++) {
		resources_list[i] = calloc(RESOURCES_MAX_SIZE + 1, sizeof(char));
		fgets(line, sizeof(line), file2);
		// Copy the line to user_ids_list[i]
    	strcpy(resources_list[i], line);
    	// Ensure null-termination
    	resources_list[i][RESOURCES_MAX_SIZE] = '\0';
	}
	fclose(file2);

	// APPROVALS.DB
	file3 = fopen(approvals, "r");
    if (file3 == NULL) {
        perror("Error opening approvals.db");
        return 1;  // Return an error code
    }

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	fclose(file3);
	exit (1);
	/* NOTREACHED */
}
