/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "check.h"

int
main (int argc, char *argv[])
{
	// Init host (server address) and client for RPC
	char *host = "127.0.0.1";
	CLIENT *clnt = clnt_create (host, CHECKPROG, CHECKVERS, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		printf("Error occured creating client to communicate with server=%s\n", host);
		exit (1);
	}

	// REQUEST
	// Request Authorization
	char *client_id;
	char **auth_token_aux = request_authorization_1(&client_id, clnt);
	if (auth_token_aux == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	char *auth_token = (char*) &auth_token_aux;

	// Approve Request Token
	char **signed_auth_token_aux = approve_request_token_1(&auth_token, clnt);
	if (signed_auth_token_aux == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	char* signed_auth_token = (char*) &signed_auth_token_aux;

	// Request Access Token
	struct request_access_token_input req_acc_token_in;
	struct request_access_token_output *req_acc_token_out = request_access_token_1(&req_acc_token_in, clnt);
	if (req_acc_token_out == (struct request_access_token_output *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	// OPERATIONS
	// Validate Delegated Action
	struct validate_delegated_action_input validate_delegated_action_1_arg;
	char **request_response_aux = validate_delegated_action_1(&validate_delegated_action_1_arg, clnt);
	if (request_response_aux == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	char *request_response = (char*) &request_response_aux;

	// Before exiting program
	clnt_destroy (clnt);
	exit (0);
}