/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CHECK_H_RPCGEN
#define _CHECK_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct request_access_token_input {
	char *client_id;
	char *auth_token;
	int refresh_duration;
};
typedef struct request_access_token_input request_access_token_input;

struct request_access_token_output {
	char *resource_access_token;
	char *refresh_token;
	int duration;
	char *request_response;
};
typedef struct request_access_token_output request_access_token_output;

struct validate_delegated_action_input {
	char *client_id;
	char *operation;
	char *resource;
	char *resource_access_token;
};
typedef struct validate_delegated_action_input validate_delegated_action_input;

struct validate_delegated_action_output {
	char *request_response;
	char *regenerated_resource_access_token;
};
typedef struct validate_delegated_action_output validate_delegated_action_output;

#define CHECKPROG 0x23072001
#define CHECKVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define request_authorization 1
extern  char ** request_authorization_1(char **, CLIENT *);
extern  char ** request_authorization_1_svc(char **, struct svc_req *);
#define request_access_token 2
extern  struct request_access_token_output * request_access_token_1(struct request_access_token_input *, CLIENT *);
extern  struct request_access_token_output * request_access_token_1_svc(struct request_access_token_input *, struct svc_req *);
#define validate_delegated_action 3
extern  struct validate_delegated_action_output * validate_delegated_action_1(struct validate_delegated_action_input *, CLIENT *);
extern  struct validate_delegated_action_output * validate_delegated_action_1_svc(struct validate_delegated_action_input *, struct svc_req *);
#define approve_request_token 4
extern  char ** approve_request_token_1(char **, CLIENT *);
extern  char ** approve_request_token_1_svc(char **, struct svc_req *);
extern int checkprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define request_authorization 1
extern  char ** request_authorization_1();
extern  char ** request_authorization_1_svc();
#define request_access_token 2
extern  struct request_access_token_output * request_access_token_1();
extern  struct request_access_token_output * request_access_token_1_svc();
#define validate_delegated_action 3
extern  struct validate_delegated_action_output * validate_delegated_action_1();
extern  struct validate_delegated_action_output * validate_delegated_action_1_svc();
#define approve_request_token 4
extern  char ** approve_request_token_1();
extern  char ** approve_request_token_1_svc();
extern int checkprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_request_access_token_input (XDR *, request_access_token_input*);
extern  bool_t xdr_request_access_token_output (XDR *, request_access_token_output*);
extern  bool_t xdr_validate_delegated_action_input (XDR *, validate_delegated_action_input*);
extern  bool_t xdr_validate_delegated_action_output (XDR *, validate_delegated_action_output*);

#else /* K&R C */
extern bool_t xdr_request_access_token_input ();
extern bool_t xdr_request_access_token_output ();
extern bool_t xdr_validate_delegated_action_input ();
extern bool_t xdr_validate_delegated_action_output ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CHECK_H_RPCGEN */
