/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "check.h"
#include "token.h"

#define SIGNATURE "###"

char **
request_authorization_1_svc(char **argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	char* clientIdToken = (char*) &argp;
	result = generate_access_token(clientIdToken);
	return &result;
}

struct request_access_token_output *
request_access_token_1_svc(struct request_access_token_input *argp, struct svc_req *rqstp)
{
	static struct request_access_token_output  result;

	/*
	 * insert server code here
	 */
	char *auth_token = argp->auth_token;
	char *client_id = argp->client_id;
	
	result.resource_access_token = generate_access_token(auth_token);
	result.refresh_token =generate_access_token(result.resource_access_token);
	result.request_response = "OK";
	result.duration = 1;
	return &result;
}

char **
validate_delegated_action_1_svc(struct validate_delegated_action_input *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */
	
	return &result;
}

char **
approve_request_token_1_svc(char **argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */
	char *token = (char*) argp;
	result = strcat(token, SIGNATURE);
	return &result;
}