/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "check.h"

char **
request_authorization_1_svc(char **argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}

struct request_access_token_output *
request_access_token_1_svc(struct request_access_token_input *argp, struct svc_req *rqstp)
{
	static struct request_access_token_output  result;

	/*
	 * insert server code here
	 */

	return &result;
}

char **
validate_delegated_action_1_svc(struct validate_delegated_action_input *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}

char **
approve_request_token_1_svc(char **argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}